name: Documentation

on: push

jobs:
  build:
    name: x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: 'build'
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: ./docs/zola
          TOKEN: ${{ secrets.TOKEN }}
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Display the path
        run: pwd
        shell: bash
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          PAGES_BRANCH: docs
          BUILD_DIR: ./docs/zola
          TOKEN: ${{ secrets.PUBLIC_TOKEN }}
          REPOSITORY: dat-adi/ff-zola
